apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: catnip
spec:
  containers:
    - name: app
      image: klim4ntovich/catnip
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      readinessProbe:
        tcpSocket:
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 2
      ports:
        - containerPort: 5000
