# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "10.0.5.10"

  config.vm.provider "virtualbox" do |vb|

    vb.gui = false
    vb.cpus = 1
    vb.memory = "1024"
  
  end

end
