# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    config.vm.box = "ubuntu/focal64"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "10.0.5.10"

    vm1.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "vm1"
      vb.cpus = "1"
      vb.memory = "512"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt install apache2 
    SHELL

  end

  config.vm.define "vm2" do |vm2|
    config.vm.box = "ubuntu/focal64"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "10.0.5.11"

    vm2.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "vm2"
      vb.cpus = "2"
      vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt update -y
        apt install nginx -y
    SHELL

  end

end
